#!/usr/bin/env python3
"""
English Technical Domain Dictionary Builder
=============================================
Generates a comprehensive English technical vocabulary JSON for domains
where professionals use English terms even while speaking Hindi:
  Civil/Construction, Finance, Science, Medical, Legal, Media,
  Transport, Military, Agriculture, Education, Technology, Sports.

Each entry has: word (English), meaning (Hindi), synonyms, category.
Same schema as master_hindi_dict.json for direct Room DB seeding.

Usage:
    python build_english_techdict.py
    python build_english_techdict.py --stats
"""

import json
import sys
import time
from pathlib import Path

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# DOMAIN DICTIONARIES
# Format: (word, meaning_hindi, synonyms)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CIVIL_CONSTRUCTION = [
    ("Shuttering", "कंक्रीट ढालने के लिए लकड़ी/स्टील का ढाँचा", "Formwork, Centering"),
    ("Formwork", "कंक्रीट के लिए साँचा/ढाँचा", "Shuttering, Mould"),
    ("Scaffolding", "ऊँचाई पर काम करने के लिए अस्थायी ढाँचा", "Staging, Platform"),
    ("Plinth", "भवन का जमीन से ऊपर का आधार भाग", "Base, Foundation level"),
    ("Foundation", "भवन की नींव", "Base, Footing, Substructure"),
    ("Footing", "नींव का निचला चौड़ा हिस्सा", "Foundation base, Pad"),
    ("PCC", "प्लेन सीमेंट कंक्रीट - बिना सरिये का कंक्रीट", "Plain Cement Concrete"),
    ("RCC", "सरिये वाला प्रबलित सीमेंट कंक्रीट", "Reinforced Cement Concrete"),
    ("Concrete", "सीमेंट, रेत और गिट्टी का मिश्रण", ""),
    ("Cement", "भवन निर्माण का बंधक पदार्थ", "Binding material"),
    ("Mortar", "सीमेंट और रेत का मिश्रण जो ईंटें जोड़ता है", "Plaster mix"),
    ("Aggregate", "कंक्रीट में मिलाई जाने वाली गिट्टी/बजरी", "Gravel, Ballast, Gitti"),
    ("Reinforcement", "कंक्रीट में डाला जाने वाला सरिया/लोहा", "Rebar, Steel bars, Sariya"),
    ("Rebar", "कंक्रीट मजबूत करने वाला सरिया", "Reinforcement bar, TMT bar, Sariya"),
    ("TMT Bar", "थर्मो मैकेनिकली ट्रीटेड सरिया", "Rebar, Reinforcement bar"),
    ("Stirrup", "सरियों को बाँधने वाला छोटा लोहे का फ्रेम", "Ring, Binding wire frame"),
    ("Beam", "भवन का क्षैतिज भार वहन करने वाला ढाँचा", "Girder, Lintel"),
    ("Column", "भवन का खड़ा खंभा जो भार सहता है", "Pillar, Post, Pier"),
    ("Slab", "छत की समतल कंक्रीट पट्टी", "Roof slab, Floor slab"),
    ("Lintel", "दरवाजे/खिड़की के ऊपर का बीम", "Header beam"),
    ("Chajja", "खिड़की/दरवाजे के ऊपर बाहर निकला छज्जा", "Sunshade, Canopy, Overhang"),
    ("Parapet", "छत के किनारे की दीवार/मुंडेर", "Railing wall, Boundary wall"),
    ("Plaster", "दीवार पर सीमेंट-रेत की परत चढ़ाना", "Rendering, Pargetting"),
    ("Curing", "कंक्रीट को पानी से गीला रखने की प्रक्रिया", "Water curing, Moisture treatment"),
    ("Levelling", "जमीन या सतह को समतल करना", "Grading, Flattening"),
    ("Survey", "जमीन का नक्शा/माप निकालना", "Land survey, Measurement"),
    ("Theodolite", "जमीन के कोण मापने का उपकरण", "Transit, Total station"),
    ("Blueprint", "भवन का विस्तृत नक्शा/डिज़ाइन", "Plan, Drawing, Layout"),
    ("Layout", "निर्माण स्थल पर नक्शे के अनुसार निशान लगाना", "Setting out, Marking"),
    ("Excavation", "नींव के लिए मिट्टी खोदना", "Digging, Trenching"),
    ("Backfill", "खुदाई के बाद मिट्टी वापस भरना", "Refilling, Earth filling"),
    ("Compaction", "मिट्टी को दबाकर मजबूत करना", "Tamping, Consolidation"),
    ("Pile", "गहरी नींव के लिए जमीन में गाड़ा जाने वाला खंभा", "Deep foundation, Boring pile"),
    ("Retaining Wall", "मिट्टी का दबाव सहने वाली दीवार", "Support wall"),
    ("DPC", "नमी रोकने वाली कंक्रीट/रसायन की परत", "Damp Proof Course"),
    ("Waterproofing", "पानी/नमी रोकने का उपचार", "Damp proofing, Sealing"),
    ("Bitumen", "सड़क बनाने में इस्तेमाल होने वाला काला चिपचिपा पदार्थ", "Asphalt, Tar"),
    ("Asphalt", "सड़क की काली परत/बिटुमिन मिश्रण", "Bitumen, Tar, Blacktop"),
    ("Grout", "दरारों/जोड़ों में भरा जाने वाला तरल सीमेंट मिश्रण", "Filler, Sealant"),
    ("JCB", "खुदाई करने वाली बड़ी मशीन", "Excavator, Backhoe, Poclain"),
    ("Crane", "भारी सामान उठाने वाली मशीन", "Hoist, Derrick, Tower crane"),
    ("Mixer", "कंक्रीट मिलाने की मशीन", "Concrete mixer, Batching plant"),
    ("Vibrator", "कंक्रीट से हवा निकालने वाली मशीन", "Needle vibrator, Poker"),
    ("Bulldozer", "मिट्टी हटाने/समतल करने वाली भारी मशीन", "Dozer, Earthmover"),
    ("Roller", "सड़क/मिट्टी दबाने वाली भारी गोल मशीन", "Compactor, Road roller"),
    ("Rising Main", "पानी ऊपर चढ़ाने वाली मुख्य पाइपलाइन", "Water main, Supply pipe"),
    ("Manhole", "सीवर/पाइपलाइन की जाँच के लिए ढक्कन वाला गड्ढा", "Inspection chamber"),
    ("Septic Tank", "गंदे पानी को साफ करने का भूमिगत टैंक", "Sewage tank"),
    ("STP", "सीवेज ट्रीटमेंट प्लांट - गंदा पानी साफ करने का संयंत्र", "Sewage Treatment Plant"),
    ("BOQ", "निर्माण सामग्री और काम की मात्रा का विवरण", "Bill of Quantities"),
    ("Estimate", "निर्माण की अनुमानित लागत", "Cost estimation, Budget"),
    ("Tender", "निर्माण कार्य के लिए बोली/निविदा", "Bid, Quotation"),
    ("Contractor", "ठेकेदार - निर्माण कार्य करवाने वाला व्यक्ति", "Builder, Thekedar"),
    ("Sub-contractor", "मुख्य ठेकेदार के नीचे काम करने वाला ठेकेदार", "Petty contractor"),
    ("Site Engineer", "निर्माण स्थल पर काम देखने वाला इंजीनियर", "Field engineer"),
    ("Supervisor", "काम की निगरानी करने वाला", "Overseer, Foreman, Mistri"),
    ("Mason", "ईंट/पत्थर लगाने वाला कारीगर", "Rajgir, Bricklayer"),
    ("Carpenter", "लकड़ी का काम करने वाला कारीगर", "Barhai, Woodworker"),
    ("Plumber", "पानी की पाइपलाइन लगाने वाला", "Pipefitter"),
    ("Electrician", "बिजली का काम करने वाला मिस्त्री", "Wireman"),
    ("Welder", "लोहा जोड़ने वाला कारीगर", ""),
    ("Labour", "मजदूर/श्रमिक", "Worker, Mazdoor, Beldar"),
    ("Centering", "स्लैब ढालने के लिए नीचे लगाया जाने वाला सहारा", "Propping, Shoring"),
    ("De-shuttering", "कंक्रीट सूखने के बाद शटरिंग हटाना", "Stripping, Formwork removal"),
    ("Grouting", "दरारों में सीमेंट का घोल भरना", "Cement injection, Filling"),
    ("Underpinning", "कमजोर नींव को मजबूत करने की तकनीक", "Foundation strengthening"),
    ("Expansion Joint", "भवन में गर्मी से फैलाव सहने का जोड़", "Movement joint"),
    ("Ramp", "ढलान वाला रास्ता", "Slope, Incline"),
    ("Staircase", "सीढ़ी", "Steps, Stairs"),
    ("Balustrade", "सीढ़ी/बालकनी की रेलिंग", "Handrail, Railing, Bannister"),
    ("Canopy", "प्रवेश द्वार पर छाया/शेड", "Porch, Awning, Chajja"),
    ("Precast", "पहले से ढाला हुआ कंक्रीट का टुकड़ा", "Prefabricated"),
    ("Ready Mix", "फैक्ट्री में तैयार कंक्रीट जो ट्रक से आता है", "RMC, Pre-mixed concrete"),
    ("Slump Test", "कंक्रीट की गुणवत्ता जाँचने का परीक्षण", "Consistency test"),
    ("Cube Test", "कंक्रीट की मजबूती जाँचने का परीक्षण", "Compressive strength test"),
    ("Grade", "कंक्रीट की मजबूती का स्तर जैसे M20, M25", "Mix ratio, Strength class"),
    ("M20", "20 न्यूटन प्रति वर्ग मिमी मजबूती वाला कंक्रीट", "Grade 20"),
    ("M25", "25 न्यूटन प्रति वर्ग मिमी मजबूती वाला कंक्रीट", "Grade 25"),
    ("Cover", "सरिये के ऊपर कंक्रीट की सुरक्षा परत की मोटाई", "Clear cover, Concrete cover"),
    ("Tie Wire", "सरिये बाँधने का पतला तार", "Binding wire, GI wire"),
    ("Spacer", "सरिये और शटरिंग के बीच दूरी बनाए रखने वाला टुकड़ा", "Cover block, Chair"),
    ("Brick", "ईंट - पकी हुई मिट्टी का टुकड़ा", ""),
    ("Block", "सीमेंट/कंक्रीट का बड़ा ब्लॉक जो ईंट की जगह इस्तेमाल होता है", "Hollow block, Solid block"),
    ("Tile", "फर्श/दीवार पर लगाई जाने वाली टाइल", "Ceramic tile, Vitrified tile"),
    ("Granite", "कठोर प्राकृतिक पत्थर जो फर्श/किचन में लगता है", ""),
    ("Marble", "संगमरमर - सफेद चमकदार पत्थर", ""),
    ("Sand", "रेत/बालू", "Fine aggregate, Bajri"),
    ("Gravel", "बजरी/गिट्टी", "Coarse aggregate, Stone chips"),
    ("Steel", "इस्पात/लोहा जो निर्माण में इस्तेमाल होता है", "Iron, TMT"),
    ("Aluminium", "हल्की धातु जो खिड़की/दरवाजों में लगती है", ""),
    ("UPVC", "खिड़की/पाइप में इस्तेमाल होने वाला प्लास्टिक", "Unplasticized PVC"),
    ("GI Pipe", "जस्ते की परत चढ़ी लोहे की पाइप", "Galvanized Iron Pipe"),
    ("CPVC Pipe", "गर्म पानी की प्लास्टिक पाइप", ""),
    ("SWR Pipe", "गंदे पानी की पाइप", "Soil Waste Rain pipe"),
    ("Bore Well", "जमीन में गहरा छेद कर पानी निकालने का कुआँ", "Tube well, Boring"),
    ("Overhead Tank", "छत पर रखी पानी की टंकी", "Syntax tank, Water tank"),
    ("Sump", "जमीन के अंदर बनी पानी की टंकी", "Underground tank"),
    ("Pump", "पानी खींचने/चढ़ाने की मशीन", "Motor, Submersible"),
    ("Valve", "पानी/गैस का बहाव रोकने/चालू करने का उपकरण", "Tap, Stopcock"),
    ("Inspection", "निर्माण कार्य की गुणवत्ता जाँच", "Quality check, Audit"),
    ("NOC", "अनापत्ति प्रमाण पत्र", "No Objection Certificate"),
    ("Completion Certificate", "भवन निर्माण पूर्ण होने का प्रमाण पत्र", "CC, Occupancy certificate"),
    ("Approval", "सरकारी मंजूरी/अनुमोदन", "Sanction, Permission"),
    ("Setback", "भवन और सड़क/सीमा के बीच छोड़ी जाने वाली खाली जगह", "Margin, Offset"),
    ("FAR", "जमीन के क्षेत्रफल के अनुपात में बनाया जा सकने वाला कुल क्षेत्रफल", "Floor Area Ratio"),
    ("Built-up Area", "दीवारों सहित भवन का कुल क्षेत्रफल", "Constructed area"),
    ("Carpet Area", "दीवारों के बिना कमरे का उपयोगी क्षेत्रफल", "Usable area"),
    ("Elevation", "भवन का सामने का दृश्य/डिज़ाइन", "Front view, Facade"),
    ("Cross Section", "भवन को काटकर देखने पर दिखने वाला अंदरूनी दृश्य", "Section drawing"),
    ("Site Plan", "पूरे प्लॉट का नक्शा जिसमें भवन की स्थिति दिखती है", "Plot plan"),
    ("Contour", "जमीन की ऊँचाई दर्शाने वाली रेखा", "Elevation line"),
    ("Benchmark", "ऊँचाई मापने का संदर्भ बिंदु", "Reference point, BM"),
    ("Chain", "जमीन मापने की इकाई (66 फीट)", "Surveyor's chain"),
    ("Theodolite", "कोण मापने का सर्वेक्षण उपकरण", "Transit"),
    ("Total Station", "दूरी और कोण मापने का इलेक्ट्रॉनिक उपकरण", "ETS"),
    ("GPS", "उपग्रह से स्थिति बताने वाली प्रणाली", "Global Positioning System"),
    ("PERT", "परियोजना का समय प्रबंधन तकनीक", "Program Evaluation Review Technique"),
    ("CPM", "परियोजना की सबसे लंबी समय श्रृंखला", "Critical Path Method"),
    ("Bar Chart", "कार्य अनुसूची दर्शाने वाला चार्ट", "Gantt chart"),
    ("Milestone", "परियोजना का महत्वपूर्ण पड़ाव", "Checkpoint"),
    ("Panchayat", "ग्राम स्तर की स्थानीय शासन संस्था", "Village council"),
    ("PWD", "लोक निर्माण विभाग", "Public Works Department"),
    ("CPWD", "केंद्रीय लोक निर्माण विभाग", "Central PWD"),
    ("Jal Nigam", "जल निगम - पानी की आपूर्ति का सरकारी विभाग", "Water corporation"),
    ("NHAI", "राष्ट्रीय राजमार्ग प्राधिकरण", "National Highway Authority of India"),
    ("IRC", "भारतीय सड़क कांग्रेस - सड़क मानक तय करने वाली संस्था", "Indian Roads Congress"),
    ("IS Code", "भारतीय मानक ब्यूरो के निर्माण नियम", "Indian Standard, BIS Code"),
    ("NBC", "राष्ट्रीय भवन संहिता", "National Building Code"),
    ("RERA", "रियल एस्टेट नियामक प्राधिकरण", "Real Estate Regulatory Authority"),
]

FINANCE = [
    ("Bank", "बैंक - पैसा जमा करने और उधार देने की संस्था", ""),
    ("Account", "बैंक खाता", "Bank account, Khata"),
    ("Savings Account", "बचत खाता", "SB Account"),
    ("Current Account", "चालू खाता - व्यापार के लिए", "CA"),
    ("Fixed Deposit", "सावधि जमा - निश्चित समय के लिए जमा", "FD, Term deposit"),
    ("Recurring Deposit", "आवर्ती जमा - हर महीने जमा करने वाली योजना", "RD"),
    ("Interest", "ब्याज - जमा/उधार पर मिलने/देने वाली रकम", "Byaj"),
    ("Interest Rate", "ब्याज दर", "Rate of interest"),
    ("Compound Interest", "चक्रवृद्धि ब्याज - ब्याज पर ब्याज", "CI"),
    ("Simple Interest", "साधारण ब्याज", "SI"),
    ("EMI", "समान मासिक किस्त", "Equated Monthly Installment"),
    ("Loan", "ऋण/कर्ज़ा", "Credit, Advance, Udhaar"),
    ("Home Loan", "घर खरीदने/बनाने के लिए कर्ज़ा", "Housing loan, Mortgage"),
    ("Personal Loan", "व्यक्तिगत कर्ज़ा", "Consumer loan"),
    ("Mortgage", "संपत्ति गिरवी रखकर लिया गया कर्ज़ा", "Hypothecation, Pledge"),
    ("Collateral", "कर्ज़े की गारंटी के लिए गिरवी रखी संपत्ति", "Security, Guarantee"),
    ("Principal", "मूलधन - कर्ज़े की असली रकम बिना ब्याज के", "Capital amount"),
    ("Credit Score", "उधार चुकाने की क्षमता का अंक", "CIBIL score"),
    ("CIBIL", "क्रेडिट स्कोर देने वाली संस्था", "Credit bureau"),
    ("Debit", "खाते से पैसा कटना/निकलना", "Withdrawal"),
    ("Credit", "खाते में पैसा जमा होना", "Deposit"),
    ("Transaction", "लेन-देन", "Transfer, Payment"),
    ("NEFT", "एक बैंक से दूसरे बैंक में पैसा भेजने की प्रणाली", "National Electronic Funds Transfer"),
    ("RTGS", "बड़ी रकम तुरंत भेजने की प्रणाली", "Real Time Gross Settlement"),
    ("IMPS", "तुरंत मोबाइल से पैसा भेजने की सेवा", "Immediate Payment Service"),
    ("UPI", "मोबाइल से भुगतान की एकीकृत प्रणाली", "Unified Payments Interface"),
    ("IFSC Code", "बैंक शाखा की पहचान का कोड", "Indian Financial System Code"),
    ("Cheque", "बैंक को भुगतान का लिखित आदेश", "Check"),
    ("Demand Draft", "बैंक द्वारा जारी भुगतान पत्र", "DD, Bank draft"),
    ("KYC", "ग्राहक की पहचान सत्यापन", "Know Your Customer"),
    ("PAN Card", "आयकर विभाग का पहचान पत्र", "Permanent Account Number"),
    ("GST", "वस्तु एवं सेवा कर", "Goods and Services Tax"),
    ("Income Tax", "आय पर लगने वाला कर", "IT"),
    ("TDS", "स्रोत पर कर कटौती", "Tax Deducted at Source"),
    ("ITR", "आयकर रिटर्न - सालाना कर विवरण", "Income Tax Return"),
    ("Audit", "खातों की जाँच/लेखा परीक्षा", "Inspection, Review"),
    ("Balance Sheet", "किसी समय की संपत्ति-देनदारी का विवरण", "Financial statement"),
    ("Profit", "लाभ/मुनाफा", "Gain, Earnings"),
    ("Loss", "हानि/नुकसान", "Deficit"),
    ("Revenue", "कुल आय/राजस्व", "Income, Turnover"),
    ("Turnover", "कुल कारोबार/बिक्री", "Sales, Revenue"),
    ("Invoice", "बिक्री का बिल/चालान", "Bill, Challan"),
    ("Ledger", "खाता बही", "Account book"),
    ("Budget", "बजट - आय-व्यय की योजना", "Financial plan"),
    ("Subsidy", "सरकारी सहायता/अनुदान", "Grant, Aid"),
    ("Insurance", "बीमा", "Coverage, Policy"),
    ("Premium", "बीमा किस्त", "Insurance premium"),
    ("Claim", "बीमा का दावा", ""),
    ("Policy", "बीमा पॉलिसी", "Insurance plan"),
    ("Mutual Fund", "कई निवेशकों का पैसा मिलाकर निवेश करने वाला फंड", "MF"),
    ("SIP", "हर महीने म्यूचुअल फंड में निश्चित रकम लगाना", "Systematic Investment Plan"),
    ("Stock", "शेयर/हिस्सेदारी", "Share, Equity"),
    ("Share Market", "शेयर बाज़ार", "Stock market, Equity market"),
    ("BSE", "बॉम्बे स्टॉक एक्सचेंज", "Bombay Stock Exchange"),
    ("NSE", "नेशनल स्टॉक एक्सचेंज", "National Stock Exchange"),
    ("Sensex", "BSE का प्रमुख सूचकांक", "BSE Index"),
    ("Nifty", "NSE का प्रमुख सूचकांक", "Nifty 50"),
    ("IPO", "कंपनी द्वारा पहली बार शेयर बेचना", "Initial Public Offering"),
    ("Dividend", "कंपनी द्वारा शेयरधारकों को दिया जाने वाला मुनाफे का हिस्सा", ""),
    ("Bond", "सरकार/कंपनी का ऋण पत्र", "Debenture"),
    ("Debenture", "कंपनी का कर्ज़ पत्र जिस पर ब्याज मिलता है", "Bond"),
    ("Portfolio", "निवेश का समूह", "Investment portfolio"),
    ("Asset", "संपत्ति/परिसंपत्ति", "Property, Holdings"),
    ("Liability", "देनदारी/ऋण", "Debt, Obligation"),
    ("Equity", "शेयर पूंजी/हिस्सेदारी", "Share capital, Ownership"),
    ("Capital", "पूंजी/धन", "Funds, Investment"),
    ("ROI", "निवेश पर प्रतिफल", "Return on Investment"),
    ("Depreciation", "संपत्ति के मूल्य में गिरावट", "Wear and tear"),
    ("Inflation", "महँगाई दर - वस्तुओं की कीमत बढ़ना", "Price rise"),
    ("Deflation", "वस्तुओं की कीमतों में गिरावट", "Price fall"),
    ("GDP", "सकल घरेलू उत्पाद - देश की कुल आय", "Gross Domestic Product"),
    ("Fiscal Year", "वित्तीय वर्ष (अप्रैल-मार्च)", "FY, Financial year"),
    ("Quarter", "तिमाही - तीन महीने की अवधि", "Q1 Q2 Q3 Q4"),
    ("Bankruptcy", "दिवालियापन - कर्ज़ चुकाने में असमर्थता", "Insolvency"),
    ("NPA", "बैंक का वो कर्ज़ जो वापस नहीं आ रहा", "Non Performing Asset, Bad loan"),
    ("RBI", "भारतीय रिज़र्व बैंक - केंद्रीय बैंक", "Reserve Bank of India"),
    ("SEBI", "शेयर बाज़ार का नियामक", "Securities and Exchange Board of India"),
    ("Fintech", "वित्तीय तकनीक - डिजिटल वित्तीय सेवाएँ", "Financial technology"),
    ("Cryptocurrency", "डिजिटल मुद्रा जैसे बिटकॉइन", "Crypto, Digital currency"),
    ("Blockchain", "विकेन्द्रीकृत डिजिटल लेनदेन की तकनीक", "Distributed ledger"),
    ("Wallet", "डिजिटल भुगतान का वॉलेट", "E-wallet, Digital wallet"),
    ("Cashback", "खरीदारी पर वापस मिलने वाला पैसा", "Refund, Reward"),
]

SCIENCE_TECH = [
    ("Algorithm", "किसी समस्या को हल करने के चरणबद्ध निर्देश", "Logic, Method"),
    ("Software", "कंप्यूटर को चलाने वाले प्रोग्राम", "Application, Program"),
    ("Hardware", "कंप्यूटर के भौतिक उपकरण/पुर्जे", "Device, Equipment"),
    ("Database", "व्यवस्थित रूप से संग्रहित डेटा का भंडार", "DB, Data store"),
    ("Server", "अन्य कंप्यूटरों को सेवा देने वाला कंप्यूटर", "Host"),
    ("Cloud", "इंटरनेट पर डेटा संग्रहण और कंप्यूटिंग", "Cloud computing"),
    ("API", "दो सॉफ्टवेयर को जोड़ने का तरीका", "Application Programming Interface"),
    ("Bandwidth", "इंटरनेट की डेटा ले जाने की क्षमता", "Speed, Data rate"),
    ("Latency", "डेटा भेजने में लगने वाला समय/देरी", "Delay, Response time"),
    ("Encryption", "डेटा को सुरक्षित कोड में बदलना", "Coding, Ciphering"),
    ("Firewall", "कंप्यूटर को अनधिकृत पहुँच से बचाने वाली सुरक्षा प्रणाली", "Security wall"),
    ("Router", "इंटरनेट सिग्नल बाँटने वाला उपकरण", "Gateway, Modem"),
    ("Processor", "कंप्यूटर का मुख्य गणना करने वाला चिप", "CPU, Chip"),
    ("RAM", "कंप्यूटर की अस्थायी तेज़ मेमोरी", "Random Access Memory"),
    ("SSD", "तेज़ गति वाली ठोस अवस्था भंडारण ड्राइव", "Solid State Drive"),
    ("GPU", "ग्राफिक्स और भारी गणना करने वाला प्रोसेसर", "Graphics Processing Unit"),
    ("AI", "कृत्रिम बुद्धिमत्ता - मशीन द्वारा सोचने जैसा काम", "Artificial Intelligence"),
    ("Machine Learning", "मशीन का डेटा से सीखना", "ML"),
    ("Deep Learning", "कृत्रिम तंत्रिका नेटवर्क से सीखना", "Neural network learning"),
    ("IoT", "इंटरनेट से जुड़े स्मार्ट उपकरण", "Internet of Things"),
    ("Sensor", "तापमान/गति/प्रकाश आदि मापने वाला उपकरण", "Detector"),
    ("Drone", "बिना पायलट का उड़ने वाला उपकरण", "UAV, Unmanned Aerial Vehicle"),
    ("Satellite", "पृथ्वी की कक्षा में घूमने वाला उपकरण", "Upagrah"),
    ("Frequency", "तरंग की आवृत्ति - प्रति सेकंड कंपन", "Hz, Hertz"),
    ("Wavelength", "तरंग की लंबाई", "Lambda"),
    ("Spectrum", "तरंगों का पूरा दायरा जैसे प्रकाश स्पेक्ट्रम", "Range"),
    ("Radiation", "ऊर्जा का विकिरण/उत्सर्जन", "Emission"),
    ("Nuclear", "परमाणु से संबंधित", "Atomic"),
    ("Reactor", "नियंत्रित परमाणु प्रतिक्रिया का संयंत्र", "Nuclear reactor"),
    ("Isotope", "एक ही तत्व के अलग-अलग भारी/हल्के रूप", ""),
    ("Catalyst", "रासायनिक प्रक्रिया तेज़ करने वाला पदार्थ", "Enzyme"),
    ("Molecule", "दो या अधिक परमाणुओं से बना कण", "Anu"),
    ("Atom", "पदार्थ का सबसे छोटा कण", "Parmanu"),
    ("Electron", "ऋणात्मक आवेश वाला परमाणु कण", ""),
    ("Proton", "धनात्मक आवेश वाला परमाणु कण", ""),
    ("Neutron", "बिना आवेश वाला परमाणु कण", ""),
    ("Gravity", "गुरुत्वाकर्षण - पृथ्वी का खींचने वाला बल", "Gravitational force"),
    ("Velocity", "किसी दिशा में गति", "Speed"),
    ("Acceleration", "गति में वृद्धि की दर", "त्वरण"),
    ("Momentum", "गति और द्रव्यमान का गुणनफल", "संवेग"),
    ("Thermodynamics", "ऊष्मा और ऊर्जा का विज्ञान", "Heat science"),
    ("Photosynthesis", "पौधों द्वारा सूर्य की रोशनी से भोजन बनाना", "प्रकाश संश्लेषण"),
    ("DNA", "जीवों की आनुवांशिक जानकारी का अणु", "Deoxyribonucleic Acid"),
    ("RNA", "प्रोटीन बनाने में मदद करने वाला अणु", "Ribonucleic Acid"),
    ("Gene", "आनुवांशिक गुणों की इकाई", "जीन"),
    ("Chromosome", "कोशिका में जीन ले जाने वाली संरचना", "गुणसूत्र"),
    ("Genome", "किसी जीव की पूरी आनुवांशिक जानकारी", "जीनोम"),
    ("Biotechnology", "जैविक प्रक्रियाओं का तकनीकी उपयोग", "Biotech"),
    ("Nanotechnology", "अत्यंत सूक्ष्म स्तर पर तकनीक", "Nanotech"),
    ("Robotics", "रोबोट बनाने और चलाने का विज्ञान", ""),
    ("3D Printing", "त्रिआयामी वस्तुएँ छापने की तकनीक", "Additive manufacturing"),
    ("Semiconductor", "अर्धचालक - बिजली आंशिक रूप से गुजारने वाला पदार्थ", "Chip material"),
    ("Transistor", "विद्युत संकेत बढ़ाने/स्विच करने वाला पुर्जा", ""),
    ("Circuit", "विद्युत का पूरा पथ/सर्किट", "Electric circuit"),
    ("Voltage", "विद्युत दबाव/वोल्टेज", "Potential difference"),
    ("Current", "विद्युत धारा", "Ampere, Flow"),
    ("Resistance", "विद्युत प्रवाह का विरोध", "Ohm, Impedance"),
    ("Watt", "बिजली की शक्ति की इकाई", "Power unit"),
    ("Kilowatt", "एक हजार वॉट", "kW"),
    ("Solar Panel", "सूर्य की रोशनी से बिजली बनाने वाला पैनल", "PV panel, Solar cell"),
    ("Inverter", "DC बिजली को AC में बदलने वाला उपकरण", "Power inverter"),
    ("Battery", "विद्युत ऊर्जा संचित करने वाला उपकरण", "Cell, Accumulator"),
    ("Lithium Ion", "आधुनिक रिचार्जेबल बैटरी की तकनीक", "Li-ion"),
    ("Renewable Energy", "नवीकरणीय ऊर्जा जैसे सौर, पवन", "Green energy, Clean energy"),
    ("Carbon Footprint", "कार्बन उत्सर्जन की मात्रा", "Emission"),
    ("Fiber Optic", "रोशनी से डेटा भेजने वाला पतला तार", "Optical fiber"),
    ("5G", "पाँचवीं पीढ़ी का मोबाइल नेटवर्क", "Fifth generation network"),
    ("Bluetooth", "कम दूरी का वायरलेस कनेक्शन", "BT"),
    ("WiFi", "वायरलेस इंटरनेट कनेक्शन", "Wireless LAN"),
    ("Cybersecurity", "इंटरनेट/कंप्यूटर की सुरक्षा", "IT security"),
    ("Malware", "कंप्यूटर को नुकसान पहुँचाने वाला सॉफ्टवेयर", "Virus, Trojan"),
    ("Phishing", "धोखाधड़ी से जानकारी चुराने का तरीका", "Online fraud"),
    ("VPN", "इंटरनेट पर सुरक्षित निजी कनेक्शन", "Virtual Private Network"),
    ("Debugging", "सॉफ्टवेयर की गलतियाँ ढूँढना और ठीक करना", "Bug fixing"),
    ("Compiler", "प्रोग्राम को मशीन भाषा में बदलने वाला सॉफ्टवेयर", ""),
    ("Open Source", "स्वतंत्र रूप से उपलब्ध सॉफ्टवेयर कोड", "Free software"),
    ("Framework", "सॉफ्टवेयर बनाने का तैयार ढाँचा", "Library, Toolkit"),
    ("Backend", "सॉफ्टवेयर का पीछे चलने वाला सर्वर हिस्सा", "Server-side"),
    ("Frontend", "सॉफ्टवेयर का उपयोगकर्ता को दिखने वाला हिस्सा", "Client-side, UI"),
    ("Deployment", "सॉफ्टवेयर को सर्वर पर चालू करना", "Release, Launch"),
    ("DevOps", "विकास और संचालन को जोड़ने की प्रक्रिया", "Development Operations"),
    ("Agile", "तेज़ और लचीले सॉफ्टवेयर विकास की पद्धति", "Sprint-based"),
    ("Scrum", "एजाइल का एक ढाँचा जिसमें स्प्रिंट होते हैं", "Sprint"),
]

MEDICAL = [
    ("OPD", "बाहरी रोगी विभाग", "Out Patient Department"),
    ("IPD", "भर्ती रोगी विभाग", "In Patient Department"),
    ("ICU", "गंभीर रोगियों की देखभाल इकाई", "Intensive Care Unit"),
    ("NICU", "नवजात शिशुओं की गहन चिकित्सा इकाई", "Neonatal ICU"),
    ("Operation Theater", "शल्य चिकित्सा कक्ष", "OT, Surgery room"),
    ("Surgery", "शल्य चिकित्सा/ऑपरेशन", "Operation"),
    ("Diagnosis", "रोग की पहचान/निदान", "Detection"),
    ("Prescription", "डॉक्टर द्वारा लिखी दवाइयों की पर्ची", "Rx"),
    ("Dosage", "दवाई की खुराक/मात्रा", "Dose"),
    ("Tablet", "गोली/दवाई", "Pill, Medicine"),
    ("Capsule", "कैप्सूल वाली दवाई", ""),
    ("Injection", "सुई द्वारा शरीर में दवाई देना", "Shot, Syringe"),
    ("IV Drip", "नस में चढ़ाया जाने वाला तरल", "Intravenous, Saline"),
    ("Saline", "नमक का घोल जो नस में चढ़ाया जाता है", "NS, Normal saline"),
    ("Antibiotic", "जीवाणु संक्रमण रोकने वाली दवाई", "Antibacterial"),
    ("Painkiller", "दर्द निवारक दवाई", "Analgesic, Pain reliever"),
    ("Steroid", "सूजन और एलर्जी कम करने वाली दवाई", "Corticosteroid"),
    ("Vaccine", "बीमारी से बचाव का टीका", "Immunization, Tika"),
    ("Booster", "टीके की अतिरिक्त खुराक", "Booster dose"),
    ("X-Ray", "हड्डी/अंदरूनी अंग देखने की किरण तकनीक", "Radiograph"),
    ("CT Scan", "शरीर की विस्तृत आंतरिक तस्वीर", "Computed Tomography"),
    ("MRI", "चुंबकीय तरंगों से शरीर की तस्वीर", "Magnetic Resonance Imaging"),
    ("Ultrasound", "ध्वनि तरंगों से शरीर के अंदर देखना", "Sonography, USG"),
    ("ECG", "हृदय की विद्युत गतिविधि का ग्राफ", "Electrocardiogram"),
    ("Blood Pressure", "रक्तचाप - धमनियों में खून का दबाव", "BP"),
    ("Diabetes", "मधुमेह - खून में शक्कर बढ़ने का रोग", "Sugar, Madhumeh"),
    ("Cholesterol", "खून में वसा का स्तर", "Lipids"),
    ("Hemoglobin", "खून में ऑक्सीजन ले जाने वाला प्रोटीन", "Hb"),
    ("Platelet", "खून के थक्के बनाने वाली कोशिकाएँ", "Thrombocyte"),
    ("WBC", "श्वेत रक्त कोशिका - संक्रमण से लड़ती है", "White Blood Cell"),
    ("RBC", "लाल रक्त कोशिका - ऑक्सीजन ले जाती है", "Red Blood Cell"),
    ("Thyroid", "गले की ग्रंथि जो हार्मोन बनाती है", "Thyroid gland"),
    ("Biopsy", "जाँच के लिए शरीर से ऊतक का टुकड़ा निकालना", "Tissue test"),
    ("Chemotherapy", "कैंसर का रासायनिक दवाओं से इलाज", "Chemo"),
    ("Dialysis", "गुर्दे खराब होने पर मशीन से खून साफ करना", "Hemodialysis"),
    ("Transplant", "शरीर में किसी अंग को बदलना", "Organ transplant"),
    ("Physiotherapy", "व्यायाम/मालिश से शारीरिक उपचार", "Physical therapy, PT"),
    ("Orthopedic", "हड्डी और जोड़ों का डॉक्टर/विभाग", "Bone specialist"),
    ("Cardiologist", "हृदय रोग विशेषज्ञ", "Heart specialist"),
    ("Neurologist", "मस्तिष्क और तंत्रिका रोग विशेषज्ञ", "Brain specialist"),
    ("Dermatologist", "त्वचा रोग विशेषज्ञ", "Skin specialist"),
    ("Pediatrician", "बाल रोग विशेषज्ञ", "Child specialist"),
    ("Gynecologist", "स्त्री रोग विशेषज्ञ", "Women's doctor"),
    ("ENT", "कान, नाक, गला विशेषज्ञ", "Ear Nose Throat"),
    ("Ophthalmologist", "नेत्र रोग विशेषज्ञ", "Eye specialist"),
    ("Dentist", "दंत चिकित्सक", "Dental surgeon"),
    ("Anesthesia", "ऑपरेशन में दर्द रोकने की दवा/प्रक्रिया", "Sedation, Numbing"),
    ("Ventilator", "साँस लेने में मदद करने वाली मशीन", "Breathing machine"),
    ("Oxygen", "ऑक्सीजन - साँस लेने के लिए जरूरी गैस", "O2"),
    ("Pulse Oximeter", "उँगली से ऑक्सीजन स्तर मापने वाला उपकरण", "SpO2 meter"),
    ("Stethoscope", "हृदय और फेफड़ों की आवाज सुनने का उपकरण", ""),
    ("Ambulance", "रोगी को अस्पताल ले जाने वाली गाड़ी", "Emergency vehicle"),
    ("Pathology", "रोगों की जाँच का विज्ञान/प्रयोगशाला", "Lab, Laboratory"),
    ("Pharmacy", "दवाई की दुकान/विभाग", "Medical store, Chemist"),
    ("Generic Medicine", "सस्ती बिना ब्रांड वाली दवाई", "Generic drug"),
    ("Side Effect", "दवाई का अनचाहा प्रभाव", "Adverse effect"),
    ("Allergy", "किसी चीज़ से शरीर की प्रतिकूल प्रतिक्रिया", "Sensitivity, Reaction"),
    ("Immunity", "शरीर की रोग प्रतिरोधक क्षमता", "Resistance, Defence"),
    ("BMI", "शरीर का वजन और लंबाई का अनुपात", "Body Mass Index"),
    ("Calorie", "भोजन में ऊर्जा की इकाई", "Kcal"),
]

LEGAL = [
    ("FIR", "प्रथम सूचना रिपोर्ट - पुलिस में पहली शिकायत", "First Information Report"),
    ("IPC", "भारतीय दंड संहिता", "Indian Penal Code"),
    ("CrPC", "दंड प्रक्रिया संहिता", "Code of Criminal Procedure"),
    ("CPC", "सिविल प्रक्रिया संहिता", "Code of Civil Procedure"),
    ("BNS", "भारतीय न्याय संहिता (नया कानून 2023)", "Bharatiya Nyaya Sanhita"),
    ("Section", "कानून की धारा/अनुच्छेद", "Dhara, Article"),
    ("Bail", "जमानत - अभियुक्त की रिहाई", "Surety"),
    ("Anticipatory Bail", "गिरफ्तारी से पहले की अग्रिम जमानत", "Advance bail"),
    ("Warrant", "गिरफ्तारी/तलाशी का न्यायिक आदेश", "Arrest order"),
    ("Summons", "अदालत में पेश होने का आदेश", "Court notice"),
    ("Affidavit", "शपथ पत्र - कसम खाकर दिया गया बयान", "Sworn statement"),
    ("Petition", "न्यायालय में दायर याचिका/अर्ज़ी", "Plea, Application"),
    ("PIL", "जनहित याचिका", "Public Interest Litigation"),
    ("Writ", "उच्च न्यायालय का आदेश", "Court order"),
    ("Appeal", "निचली अदालत के फैसले के खिलाफ ऊपरी अदालत में अपील", ""),
    ("Hearing", "अदालत में मुकदमे की सुनवाई", "Trial, Court date"),
    ("Verdict", "अदालत का फैसला/निर्णय", "Judgment, Order"),
    ("Acquittal", "अदालत द्वारा बरी करना/दोषमुक्त", "Not guilty"),
    ("Conviction", "अदालत द्वारा दोषी ठहराना", "Guilty verdict"),
    ("Sentence", "सज़ा का आदेश", "Punishment, Penalty"),
    ("Prosecution", "अभियोजन - सरकार की तरफ से मुकदमा चलाना", ""),
    ("Defence", "बचाव पक्ष", "Defence counsel"),
    ("Plaintiff", "वादी - मुकदमा दायर करने वाला", "Complainant"),
    ("Defendant", "प्रतिवादी - जिसके खिलाफ मुकदमा हो", "Accused"),
    ("Witness", "गवाह", "Testimony provider"),
    ("Evidence", "सबूत/साक्ष्य", "Proof"),
    ("Cross Examination", "गवाह से विपक्ष की पूछताछ", ""),
    ("Lawyer", "वकील/अधिवक्ता", "Advocate, Attorney, Counsel"),
    ("Public Prosecutor", "सरकारी वकील", "PP, State counsel"),
    ("Magistrate", "न्यायाधीश (निचली अदालत)", "Judge, Judicial magistrate"),
    ("High Court", "उच्च न्यायालय", "HC"),
    ("Supreme Court", "सर्वोच्च न्यायालय", "SC, Apex court"),
    ("District Court", "जिला न्यायालय", "Sessions court"),
    ("Tribunal", "विशेष मामलों की न्यायिक संस्था", "Bench"),
    ("Arbitration", "पंच फैसला - अदालत के बाहर विवाद निपटान", "Mediation"),
    ("Mediation", "मध्यस्थता से विवाद सुलझाना", "Conciliation"),
    ("Copyright", "रचना का कानूनी अधिकार", "IP, Intellectual property"),
    ("Patent", "आविष्कार का एकाधिकार पत्र", ""),
    ("Trademark", "व्यापार चिह्न/ब्रांड का कानूनी संरक्षण", "Brand protection"),
    ("Power of Attorney", "मुख्तारनामा - किसी को अपनी ओर से काम करने का अधिकार", "POA"),
    ("Notary", "नोटरी - दस्तावेजों को प्रमाणित करने वाला अधिकारी", ""),
    ("Stamp Duty", "दस्तावेजों पर लगने वाला सरकारी शुल्क", "Registration fee"),
    ("Registry", "संपत्ति का सरकारी पंजीकरण", "Registration"),
    ("Mutation", "राजस्व रिकॉर्ड में मालिकाना हक बदलना", "Dakhil kharij, Intkal"),
    ("Encumbrance", "संपत्ति पर कानूनी बोझ/बंधन", "Lien"),
    ("Stay Order", "अदालत का रोक आदेश", "Injunction"),
    ("Contempt of Court", "न्यायालय की अवमानना", ""),
    ("Habeas Corpus", "गैरकानूनी हिरासत के खिलाफ याचिका", ""),
    ("RTI", "सूचना का अधिकार", "Right to Information"),
    ("Consumer Forum", "उपभोक्ता शिकायत निवारण मंच", "Consumer court"),
    ("Cybercrime", "इंटरनेट/कंप्यूटर से जुड़ा अपराध", "Online fraud, Hacking"),
    ("POCSO", "बच्चों के यौन शोषण से संरक्षण का कानून", "Protection of Children from Sexual Offences"),
    ("Dowry Act", "दहेज प्रतिषेध अधिनियम", "Dowry Prohibition Act"),
    ("Domestic Violence", "घरेलू हिंसा", "DV Act"),
    ("Custody", "हिरासत/अभिरक्षा", "Guardianship"),
    ("Alimony", "तलाक के बाद पत्नी को दिया जाने वाला भरण-पोषण", "Maintenance"),
    ("Settlement", "आपसी समझौता/सुलह", "Compromise"),
]

MEDIA = [
    ("Broadcast", "प्रसारण - रेडियो/टीवी पर कार्यक्रम भेजना", "Telecast, Transmission"),
    ("Live", "सीधा प्रसारण", "Real-time"),
    ("Breaking News", "ताज़ा खबर/तत्काल समाचार", "Flash news"),
    ("Headline", "मुख्य समाचार शीर्षक", "Top story"),
    ("Anchor", "समाचार प्रस्तुतकर्ता", "News reader, Presenter"),
    ("Reporter", "संवाददाता/पत्रकार", "Journalist, Correspondent"),
    ("Editor", "संपादक", "Chief editor"),
    ("Press Conference", "पत्रकार सम्मेलन", "Media briefing"),
    ("Press Release", "मीडिया के लिए आधिकारिक बयान", "Media statement"),
    ("Exclusive", "विशेष/अनन्य खबर", "Scoop"),
    ("Source", "खबर का स्रोत/सूत्र", "Informant"),
    ("Column", "समाचार पत्र में नियमित लेख", "Opinion piece"),
    ("Editorial", "संपादकीय लेख", "Op-ed"),
    ("Podcast", "ऑनलाइन ऑडियो कार्यक्रम", "Audio show"),
    ("Streaming", "इंटरनेट पर सीधे वीडियो/ऑडियो देखना-सुनना", "Online viewing"),
    ("Viral", "तेज़ी से फैलने वाली सामग्री", "Trending"),
    ("Content", "सामग्री - लेख, वीडियो, फोटो आदि", "Media content"),
    ("Subscribers", "चैनल/सेवा के सदस्य", "Followers"),
    ("Viewership", "दर्शकों की संख्या", "TRP, Audience"),
    ("TRP", "टीवी चैनल की लोकप्रियता मापने का पैमाना", "Television Rating Point"),
    ("Documentary", "तथ्य आधारित फिल्म/कार्यक्रम", "Docu"),
    ("Script", "फिल्म/कार्यक्रम की पटकथा", "Screenplay"),
    ("Editing", "वीडियो/ऑडियो काटना-जोड़ना", "Post-production"),
    ("Dubbing", "किसी भाषा में आवाज़ बदलना", "Voice over"),
    ("Subtitles", "स्क्रीन पर लिखित अनुवाद", "Captions"),
    ("Thumbnail", "वीडियो की छोटी प्रदर्शन तस्वीर", "Preview image"),
    ("SEO", "गूगल खोज में ऊपर आने की तकनीक", "Search Engine Optimization"),
    ("Analytics", "डेटा विश्लेषण/आँकड़े", "Insights, Statistics"),
    ("Engagement", "दर्शकों की सक्रिय भागीदारी", "Likes, Comments, Shares"),
    ("Influencer", "सोशल मीडिया पर प्रभावशाली व्यक्ति", "Creator, Blogger"),
    ("Monetization", "सामग्री से पैसा कमाना", "Revenue generation"),
    ("Copyright Strike", "बिना अनुमति सामग्री इस्तेमाल पर कानूनी चेतावनी", "DMCA"),
    ("Fact Check", "खबर/दावे की सत्यता जाँच", "Verification"),
    ("Fake News", "झूठी/भ्रामक खबर", "Misinformation, Propaganda"),
    ("Censorship", "सामग्री पर सरकारी प्रतिबंध/कटौती", "Ban"),
]

TRANSPORT = [
    ("Highway", "राजमार्ग/राष्ट्रीय सड़क", "National Highway, NH"),
    ("Expressway", "द्रुतगामी मार्ग - तेज़ गति की सड़क", "Motorway"),
    ("Flyover", "सड़क के ऊपर बना पुल", "Overpass, Elevated road"),
    ("Underpass", "सड़क के नीचे का रास्ता", "Subway, Tunnel"),
    ("Toll Plaza", "राजमार्ग पर शुल्क वसूली केंद्र", "Toll booth, Toll gate"),
    ("FASTag", "टोल का इलेक्ट्रॉनिक भुगतान उपकरण", "Electronic toll"),
    ("Divider", "सड़क के बीच का विभाजक", "Median, Separator"),
    ("Footpath", "पैदल चलने का रास्ता", "Sidewalk, Pavement"),
    ("Zebra Crossing", "पैदल पार पट्टी", "Pedestrian crossing"),
    ("Traffic Signal", "यातायात बत्ती", "Traffic light, Red light"),
    ("Speed Limit", "अधिकतम गति सीमा", ""),
    ("Overtaking", "आगे निकलना", "Passing"),
    ("Lane", "सड़क पर वाहन चलने की पट्टी", "Track"),
    ("Roundabout", "गोलचक्कर", "Traffic circle, Rotary"),
    ("Parking", "वाहन खड़ा करने की जगह", ""),
    ("Metro", "शहर की भूमिगत/ऊपरी रेल सेवा", "Subway, Urban rail"),
    ("Monorail", "एक पटरी पर चलने वाली रेल", ""),
    ("Bullet Train", "अत्यधिक तेज़ गति की ट्रेन", "High speed rail"),
    ("Platform", "रेलवे स्टेशन पर ट्रेन का प्लेटफॉर्म", ""),
    ("Terminal", "हवाई अड्डे/बस अड्डे की इमारत", ""),
    ("Runway", "हवाई जहाज़ उड़ने/उतरने का रास्ता", "Airstrip"),
    ("Hangar", "हवाई जहाज़ रखने का बड़ा शेड", "Aircraft shed"),
    ("Cargo", "माल/सामान जो एक जगह से दूसरी जगह भेजा जाता है", "Freight, Shipment"),
    ("Logistics", "माल ढुलाई और आपूर्ति श्रृंखला प्रबंधन", "Supply chain"),
    ("Container", "माल भेजने का बड़ा धातु का डिब्बा", "Shipping container"),
    ("GPS Tracker", "वाहन की स्थिति बताने वाला उपकरण", "Vehicle tracker"),
    ("Diesel", "डीज़ल ईंधन", ""),
    ("Petrol", "पेट्रोल ईंधन", "Gasoline"),
    ("CNG", "कम्प्रेस्ड नेचुरल गैस - प्राकृतिक गैस ईंधन", "Compressed Natural Gas"),
    ("EV", "इलेक्ट्रिक वाहन", "Electric Vehicle"),
    ("Hybrid", "पेट्रोल और बिजली दोनों से चलने वाला वाहन", ""),
    ("Chassis", "वाहन का मूल ढाँचा", "Frame"),
    ("Suspension", "वाहन का झटके सहने का तंत्र", "Shock absorber"),
    ("ABS", "ब्रेक लगाने पर पहिए लॉक न होने देने वाली प्रणाली", "Anti-lock Braking System"),
    ("Airbag", "दुर्घटना में सुरक्षा का हवा वाला थैला", "Safety bag"),
    ("Emission", "वाहन से निकलने वाला धुआँ/प्रदूषण", "Exhaust, Pollution"),
    ("PUC", "वाहन प्रदूषण जाँच प्रमाण पत्र", "Pollution Under Control"),
    ("RC", "वाहन पंजीकरण प्रमाण पत्र", "Registration Certificate"),
    ("DL", "ड्राइविंग लाइसेंस - वाहन चलाने का परमिट", "Driving License"),
    ("Challan", "यातायात नियम तोड़ने पर जुर्माना", "Traffic fine, Ticket"),
]

MILITARY = [
    ("Battalion", "सेना की एक टुकड़ी (लगभग 800-1000 सैनिक)", "Paltan"),
    ("Regiment", "सेना की बड़ी इकाई", ""),
    ("Brigade", "कई बटालियनों का समूह", ""),
    ("Division", "कई ब्रिगेडों का समूह", ""),
    ("Corps", "कई डिवीज़नों का समूह", ""),
    ("Platoon", "30-50 सैनिकों का दल", ""),
    ("Company", "100-200 सैनिकों की टुकड़ी", ""),
    ("Commando", "विशेष प्रशिक्षित सैनिक", "Special forces"),
    ("Infantry", "पैदल सेना", "Foot soldiers"),
    ("Artillery", "तोपखाना/भारी हथियार विभाग", "Cannon, Guns"),
    ("Cavalry", "घुड़सवार/बख़्तरबंद सेना", "Armoured corps"),
    ("Navy", "नौसेना", "Naval force"),
    ("Air Force", "वायुसेना", "IAF"),
    ("Missile", "प्रक्षेपास्त्र/मिसाइल", "Rocket"),
    ("Torpedo", "पानी में चलने वाला विस्फोटक हथियार", ""),
    ("Radar", "रेडियो तरंगों से वस्तु का पता लगाने वाली प्रणाली", ""),
    ("Surveillance", "निगरानी/जासूसी", "Monitoring, Recon"),
    ("Intelligence", "गुप्तचर/खुफिया जानकारी", "Secret information"),
    ("Ceasefire", "युद्ध विराम/गोलीबारी बंद", "Truce"),
    ("Airstrike", "हवाई हमला", "Bombing, Air raid"),
    ("Ammunition", "गोला-बारूद", "Ammo, Munitions"),
    ("Bunker", "सुरक्षित भूमिगत ठिकाना", "Shelter"),
    ("Barracks", "सैनिकों के रहने की जगह", "Military camp"),
    ("Court Martial", "सैन्य अदालत/सैनिक की सुनवाई", "Military trial"),
    ("Deployment", "सैनिकों को तैनात करना", "Posting, Stationing"),
    ("Border", "सीमा/सरहद", "Frontier, LOC"),
    ("LOC", "नियंत्रण रेखा (भारत-पाक सीमा)", "Line of Control"),
    ("LAC", "वास्तविक नियंत्रण रेखा (भारत-चीन सीमा)", "Line of Actual Control"),
    ("Patrol", "गश्त/निगरानी दौरा", ""),
    ("Camouflage", "छद्मावरण - दुश्मन से छिपने की तकनीक", "Disguise"),
]

AGRICULTURE = [
    ("Tractor", "खेत जोतने/बोझ ढोने वाला वाहन", ""),
    ("Harvester", "फसल काटने की मशीन", "Combine"),
    ("Thresher", "फसल से दाना अलग करने की मशीन", ""),
    ("Rotavator", "खेत की मिट्टी भुरभुरी करने की मशीन", "Cultivator"),
    ("Sprayer", "कीटनाशक छिड़कने की मशीन", "Spray pump"),
    ("Drip Irrigation", "बूँद-बूँद सिंचाई", "Micro irrigation"),
    ("Sprinkler", "फव्वारे से सिंचाई करने वाला उपकरण", "Rain gun"),
    ("Bore Well", "जमीन में गहरा छेद कर पानी निकालना", "Tube well"),
    ("Submersible Pump", "पानी के अंदर डूबकर चलने वाला पंप", "Boring pump"),
    ("Fertilizer", "उर्वरक/रासायनिक खाद", "Manure"),
    ("Urea", "नाइट्रोजन वाली रासायनिक खाद", ""),
    ("DAP", "फॉस्फोरस वाली खाद", "Di-Ammonium Phosphate"),
    ("NPK", "नाइट्रोजन-फॉस्फोरस-पोटाश का मिश्रित खाद", ""),
    ("Pesticide", "कीटनाशक", "Insecticide"),
    ("Herbicide", "खरपतवार नाशक", "Weedicide"),
    ("Fungicide", "फफूंदनाशक", "Antifungal"),
    ("Organic Farming", "जैविक/प्राकृतिक खेती", "Chemical-free farming"),
    ("Vermicompost", "केंचुआ खाद", "Worm compost"),
    ("Crop Rotation", "फसल चक्र - बारी-बारी अलग फसल उगाना", ""),
    ("Hybrid Seed", "संकर बीज - दो किस्मों को मिलाकर बना बीज", ""),
    ("GM Crop", "आनुवांशिक रूप से संशोधित फसल", "Genetically Modified"),
    ("MSP", "न्यूनतम समर्थन मूल्य - सरकार की गारंटी कीमत", "Minimum Support Price"),
    ("APMC", "कृषि उपज मंडी समिति", "Mandi, Agriculture Produce Market Committee"),
    ("Mandi", "कृषि उपज बेचने का बाज़ार", "APMC, Wholesale market"),
    ("Cold Storage", "फल/सब्जी रखने का ठंडा भंडार", "Refrigerated warehouse"),
    ("Greenhouse", "पौधे उगाने का कांच/प्लास्टिक का घर", "Polyhouse"),
    ("Polyhouse", "प्लास्टिक शीट से बना पौधाघर", "Greenhouse"),
    ("Soil Testing", "मिट्टी की जाँच", "Soil analysis"),
    ("pH Level", "मिट्टी/पानी की अम्लीयता/क्षारीयता का माप", "Acidity level"),
    ("Mulching", "पौधों के चारों ओर पत्ते/प्लास्टिक बिछाना", "Ground cover"),
    ("Transplanting", "पौधे को एक जगह से उखाड़कर दूसरी जगह लगाना", "Ropai"),
    ("Nursery", "पौधे तैयार करने की जगह", "Plant nursery"),
    ("Grafting", "एक पौधे पर दूसरे पौधे की टहनी जोड़ना", "Kalam lagana"),
    ("Yield", "प्रति एकड़ फसल की पैदावार", "Production, Output"),
    ("Kharif", "बारिश की फसल (जून-अक्तूबर)", "Monsoon crop"),
    ("Rabi", "सर्दी की फसल (अक्तूबर-मार्च)", "Winter crop"),
    ("Zaid", "गर्मी की छोटी फसल (मार्च-जून)", "Summer crop"),
    ("Watershed", "जल संग्रहण क्षेत्र", "Catchment area"),
    ("Silt", "नदी/तालाब में जमी बारीक मिट्टी", "Sediment"),
    ("Bund", "खेत के चारों ओर मिट्टी का मेड़/बाँध", "Embankment, Levee"),
    ("Canal", "सिंचाई नहर", "Irrigation channel"),
    ("Tubewell", "ज़मीन से पानी खींचने का कुआँ", "Bore well, Boring"),
    ("FPO", "किसान उत्पादक संगठन", "Farmer Producer Organization"),
    ("KCC", "किसान क्रेडिट कार्ड", "Kisan Credit Card"),
    ("PM-KISAN", "प्रधानमंत्री किसान सम्मान निधि योजना", ""),
    ("Crop Insurance", "फसल बीमा", "PMFBY"),
]

EDUCATION = [
    ("Syllabus", "पाठ्यक्रम", "Curriculum"),
    ("Semester", "छह महीने की शैक्षणिक अवधि", "Term"),
    ("Assignment", "गृहकार्य/प्रोजेक्ट", "Homework"),
    ("Thesis", "शोध प्रबंध", "Dissertation"),
    ("Research Paper", "शोध पत्र", "Journal article"),
    ("Viva", "मौखिक परीक्षा", "Oral exam"),
    ("Scholarship", "छात्रवृत्ति", "Fellowship"),
    ("Diploma", "डिप्लोमा प्रमाण पत्र", "Certificate"),
    ("Degree", "उपाधि - B.Tech, MBA, M.Sc आदि", ""),
    ("PhD", "डॉक्टरेट - सर्वोच्च शैक्षणिक उपाधि", "Doctorate"),
    ("Campus", "विश्वविद्यालय/कॉलेज का परिसर", ""),
    ("Dean", "विभागाध्यक्ष", "Head of department"),
    ("Professor", "प्राध्यापक", "Faculty"),
    ("Lecture", "कक्षा में पढ़ाना", "Class, Teaching session"),
    ("Seminar", "विषय पर चर्चा सभा", "Workshop, Conference"),
    ("Webinar", "ऑनलाइन सेमिनार", "Online seminar"),
    ("E-Learning", "इंटरनेट से पढ़ाई", "Online learning, Digital education"),
    ("MOOC", "बड़े पैमाने पर खुला ऑनलाइन पाठ्यक्रम", "Massive Open Online Course"),
    ("Plagiarism", "दूसरे का काम अपने नाम से दिखाना/चोरी", "Copying"),
    ("Accreditation", "शैक्षणिक संस्था की मान्यता", "NAAC, Recognition"),
    ("NAAC", "शिक्षा संस्थानों की गुणवत्ता मूल्यांकन संस्था", "National Assessment and Accreditation Council"),
    ("UGC", "विश्वविद्यालय अनुदान आयोग", "University Grants Commission"),
    ("AICTE", "तकनीकी शिक्षा का नियामक", "All India Council for Technical Education"),
    ("JEE", "इंजीनियरिंग प्रवेश परीक्षा", "Joint Entrance Examination"),
    ("NEET", "मेडिकल प्रवेश परीक्षा", "National Eligibility cum Entrance Test"),
    ("GATE", "स्नातकोत्तर इंजीनियरिंग प्रवेश परीक्षा", "Graduate Aptitude Test in Engineering"),
    ("CAT", "MBA प्रवेश परीक्षा", "Common Admission Test"),
    ("GPA", "ग्रेड प्वाइंट औसत", "Grade Point Average, CGPA"),
    ("Internship", "व्यावहारिक प्रशिक्षण अवधि", "Training, Apprenticeship"),
    ("Placement", "कॉलेज से सीधे नौकरी लगना", "Campus recruitment"),
]

SPORTS = [
    ("Tournament", "प्रतियोगिता/टूर्नामेंट", "Championship, Competition"),
    ("League", "लीग - टीमों के बीच नियमित मैच", ""),
    ("Semi-Final", "उपांतिम मैच", ""),
    ("Quarter-Final", "क्वार्टर फाइनल", ""),
    ("Knockout", "हार पर बाहर होने वाली प्रतियोगिता", "Elimination round"),
    ("Referee", "खेल का निर्णायक", "Umpire, Judge"),
    ("Coach", "प्रशिक्षक/कोच", "Trainer"),
    ("Captain", "टीम का कप्तान", "Skipper"),
    ("Substitute", "बदली खिलाड़ी", "Reserve, Bench player"),
    ("Hat-trick", "एक ही मैच में तीन बार सफलता", ""),
    ("Penalty", "नियम तोड़ने पर दंड", "Foul"),
    ("Offside", "नियम-विरुद्ध आगे खड़ा होना (फुटबॉल)", ""),
    ("Doping", "प्रतिबंधित दवा का सेवन", "Drug test, Banned substance"),
    ("Fitness", "शारीरिक तंदुरुस्ती", "Physical fitness"),
    ("Warm-up", "खेल से पहले शरीर गर्म करना", "Stretching"),
    ("Innings", "क्रिकेट में बल्लेबाजी की पारी", ""),
    ("Wicket", "क्रिकेट में गिल्लियाँ/आउट होना", "Stumps"),
    ("Boundary", "क्रिकेट में चौका", "Four"),
    ("Six", "क्रिकेट में छक्का", "Sixer"),
    ("LBW", "पैर के सामने आने पर आउट", "Leg Before Wicket"),
    ("Run Rate", "प्रति ओवर रन बनने की दर", "Scoring rate"),
    ("Powerplay", "क्रिकेट में फील्डिंग प्रतिबंध वाले ओवर", ""),
    ("DRS", "अंपायर के फैसले की समीक्षा प्रणाली", "Decision Review System"),
    ("Stadium", "खेल का मैदान/स्टेडियम", "Ground, Arena"),
    ("Olympics", "ओलंपिक खेल", "Olympic Games"),
    ("Medal", "पदक - स्वर्ण, रजत, कांस्य", "Gold, Silver, Bronze"),
    ("Record", "सर्वश्रेष्ठ प्रदर्शन का कीर्तिमान", "Best mark"),
    ("Marathon", "42 किमी की लंबी दौड़", "Long distance race"),
    ("Sprint", "छोटी दूरी की तेज़ दौड़", "100m, 200m race"),
    ("Relay", "टीम के सदस्यों द्वारा बारी-बारी दौड़", "Relay race"),
]


ALL_DOMAINS = {
    "Civil/Construction": CIVIL_CONSTRUCTION,
    "Finance": FINANCE,
    "Science/Technology": SCIENCE_TECH,
    "Medical": MEDICAL,
    "Legal": LEGAL,
    "Media": MEDIA,
    "Transport": TRANSPORT,
    "Military": MILITARY,
    "Agriculture": AGRICULTURE,
    "Education": EDUCATION,
    "Sports": SPORTS,
}


def build_entries(show_stats: bool = False) -> list[dict]:
    entries = []
    seen = set()
    category_counts: dict[str, int] = {}

    for category, words in ALL_DOMAINS.items():
        for word, meaning, synonyms in words:
            key = word.lower()
            if key in seen:
                continue
            seen.add(key)

            entries.append({
                "word": word,
                "meaning": meaning,
                "synonyms": synonyms,
                "category": category,
            })
            category_counts[category] = category_counts.get(category, 0) + 1

    entries.sort(key=lambda e: e["word"].lower())

    print(f"Total English technical words: {len(entries)}")
    print(f"Categories: {len(category_counts)}")

    if show_stats:
        print("\n── Category Breakdown ──")
        for cat, count in sorted(category_counts.items(), key=lambda x: -x[1]):
            print(f"  {cat:25s} → {count:>4} words")

    return entries


def main():
    show_stats = "--stats" in sys.argv
    start = time.time()

    entries = build_entries(show_stats=show_stats)

    output_path = Path(__file__).parent / "master_english_techdict.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    size_kb = output_path.stat().st_size / 1024
    elapsed = time.time() - start

    print(f"\nWritten to: {output_path}")
    print(f"File size: {size_kb:.0f} KB ({elapsed:.1f}s)")
    print(f"\nSamples:")
    for entry in entries[:5]:
        print(f"  {entry['word']}: {entry['meaning'][:60]}... [{entry['category']}]")


if __name__ == "__main__":
    main()
